export { toCapitalize } from "./capitalize";
export { toSubcategories } from "./toSubcategories";
export { getBannerImage } from "./banner-images";
export { getSortedArray } from "./get sorted array";
export { getStateOfProduct } from "./get-state-of-product";
export { getPlural } from "./get-plural";
export { getTotalPrice } from "./get-total-price";
export { updateLocalStorage } from "./update-local-storage";
export { getDiscount } from "./get-discount";
export { findItem } from "./find-item";
export { getFilterProducts } from "./get-filtered-products";
export { getCuttedText } from "./get-cutted-text";
