export interface ActionsTypes {
  ADD_TO_CART: "ADD_TO_CART";
  SUBSTRACT_COUNTER_FROM_CART: "SUBSTRACT_COUNTER_FROM_CART";
  REMOVE_FROM_CART: "REMOVE_FROM_CART";
  CLEAR_CART: "CLEAR_CART";
  INITIAL_CART: "INITIAL_CART";
  UPDATE_PRODUCT_SIZE: "UPDATE_PRODUCT_SIZE";
}
